process_id: culp_30_month_v1
source_of_truth: "https://www.gov.uk/guidance/30-month-local-plan-process-an-overview"

sequencing:
  required_by_law:
    # As summarised in the GOV.UK overview diagram (high-level, mandatory order).
    - timetable
    - notice_of_plan_making
    - scoping_consultation
    - gateway_1
    - publish_scoping_summary
    - consult_on_proposed_content_and_evidence
    - gateway_2
    - consult_on_proposed_local_plan
    - gateway_3
    - examination
    - adoption_and_publication

phases:
  - id: getting_ready_pre_30m
    title: "Getting ready (pre-30-month clock)"
    description: "Work done before Gateway 1; 30-month clock has not started."
  - id: plan_preparation_m1_23
    title: "Plan preparation (Months 1–23)"
  - id: submit_for_examination_m24_29
    title: "Submit for examination (Months 24–29)"
  - id: adopt_and_publish_m30_31
    title: "Adopt + publish (Months 30–31)"
  - id: monitor_m31_plus
    title: "Monitor (Month 31+)"

stages:

  # --- Getting ready (pre-30-month clock) ---
  - id: confirm_sea_requirement
    phase: getting_ready_pre_30m
    title: "Confirm SEA requirement"
    required_artefacts:
      - sea_requirement_record
    gov_uk_ref: "https://www.gov.uk/guidance/30-month-local-plan-process-an-overview"

  - id: timetable
    phase: getting_ready_pre_30m
    title: "Timetable"
    required_artefacts:
      - milestones_table
      - updates_log
      - project_initiation_document
    gov_uk_ref: "https://www.gov.uk/guidance/getting-ready-to-prepare-a-new-plan"

  - id: notice_of_plan_making
    phase: getting_ready_pre_30m
    title: "Give notice of plan-making"
    required_artefacts:
      - notice_html
      - boundary_map
      - geometry_download
    gov_uk_ref: "https://www.gov.uk/guidance/giving-notice-of-your-plan-making"

  - id: scoping_consultation
    phase: getting_ready_pre_30m
    title: "Scoping consultation"
    required_artefacts:
      - scoping_consultation_materials
      - consultee_list
      - responses_log
    gov_uk_ref: "https://www.gov.uk/guidance/getting-ready-to-prepare-a-new-plan"

  - id: baselining_and_place_portrait
    phase: getting_ready_pre_30m
    title: "Baselining & place portrait"
    required_artefacts:
      - place_portrait_sheet
      - evidence_base_index
    gov_uk_ref: "https://www.gov.uk/guidance/gathering-baselining-information-to-inform-a-local-plan"

  - id: gateway_1
    phase: getting_ready_pre_30m
    title: "Gateway 1 (starts the 30-month clock)"
    required_artefacts:
      - self_assessment_summary
      - readiness_checker_output
    gov_uk_ref: "https://www.gov.uk/guidance/gateway-1-what-you-need-to-do"

  - id: publish_scoping_summary
    phase: plan_preparation_m1_23
    title: "Publish scoping summary"
    required_artefacts:
      - scoping_summary_report
    gov_uk_ref: "https://www.gov.uk/guidance/30-month-local-plan-process-an-overview"

  # --- Plan preparation (Months 1–23) ---
  - id: vision_and_outcomes
    phase: plan_preparation_m1_23
    title: "Vision & outcomes"
    required_artefacts:
      - vision_statement
      - outcomes_list_max_10
    gov_uk_ref: "https://www.gov.uk/guidance/preparing-a-local-plan-vision"

  - id: options_and_evidence_development
    phase: plan_preparation_m1_23
    title: "Develop options, sites, and evidence"
    required_artefacts:
      - evidence_base_index
      - constraints_register
      - reasonable_alternatives_log
      - site_assessments_bulk
      - allocation_options_pack
    gov_uk_ref: "https://www.gov.uk/guidance/selecting-identifying-and-assessing-sites-for-local-plans"

  - id: consult_on_proposed_content_and_evidence
    phase: plan_preparation_m1_23
    title: "Consult on proposed plan content & evidence"
    required_artefacts:
      - consultation_materials_pack
      - responses_log
      - consultation_summary_report
    gov_uk_ref: "https://www.gov.uk/guidance/30-month-local-plan-process-an-overview"

  - id: gateway_2
    phase: plan_preparation_m1_23
    title: "Gateway 2"
    required_artefacts:
      - gateway_2_self_assessment
      - gateway_2_submission_pack
      - updated_timetable
    gov_uk_ref: "https://www.gov.uk/guidance/30-month-local-plan-process-an-overview"

  # --- Submit for examination (Months 24–29) ---
  - id: consult_on_proposed_local_plan
    phase: submit_for_examination_m24_29
    title: "Consult on proposed local plan"
    required_artefacts:
      - proposed_local_plan_draft
      - policy_pages_html
      - policies_map_draft
      - policies_map_layers
      - policies_map_metadata
      - responses_log
      - consultation_summary_report
      - sds_conformity_consultation_if_applicable
      - statement_of_consultation
    gov_uk_ref: "https://www.gov.uk/guidance/30-month-local-plan-process-an-overview"

  - id: gateway_3
    phase: submit_for_examination_m24_29
    title: "Gateway 3"
    required_artefacts:
      - gateway_3_self_assessment
      - gateway_3_submission_pack
      - submission_ready_pack
    gov_uk_ref: "https://www.gov.uk/guidance/30-month-local-plan-process-an-overview"

  - id: submit_for_examination
    phase: submit_for_examination_m24_29
    title: "Submit for examination"
    required_artefacts:
      - submission_bundle
      - evidence_base_index
      - consultation_statement
      - duty_to_cooperate_or_sds_materials
    gov_uk_ref: "https://www.gov.uk/guidance/30-month-local-plan-process-an-overview"

  - id: examination
    phase: submit_for_examination_m24_29
    title: "Examination"
    required_artefacts:
      - inspectors_questions_log
      - hearing_statements_bundle
      - main_modifications_if_any
    gov_uk_ref: "https://www.gov.uk/guidance/30-month-local-plan-process-an-overview"

  # --- Adopt + publish (Months 30–31) ---
  - id: adoption_and_publication
    phase: adopt_and_publish_m30_31
    title: "Adoption + publish policies map"
    required_artefacts:
      - adopted_local_plan
      - policy_pages_html
      - policies_map_final
      - policies_map_layers
      - policies_map_metadata
      - adoption_statement
    gov_uk_ref: "https://www.gov.uk/guidance/30-month-local-plan-process-an-overview"

  # --- Monitor (Month 31+) ---
  - id: monitoring_and_review
    phase: monitor_m31_plus
    title: "Monitoring & review"
    required_artefacts:
      - monitoring_framework
      - amr_or_equivalent
      - review_triggers_log
    gov_uk_ref: "https://www.gov.uk/guidance/30-month-local-plan-process-an-overview"
