import React, { useEffect, useState } from 'react';
import { X, Loader2, BookOpen, AlertCircle } from 'lucide-react';
import ReactMarkdown from 'react-markdown';
import { Site, Scenario } from '../types';
import { generateInspectorTrace } from '../services/geminiService';

interface TraceViewProps {
  scenario: Scenario;
  site: Site;
  onClose: () => void;
}

const TraceView: React.FC<TraceViewProps> = ({ scenario, site, onClose }) => {
  const [markdown, setMarkdown] = useState<string | null>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    let isMounted = true;
    const fetchTrace = async () => {
      setLoading(true);
      const result = await generateInspectorTrace(scenario, site);
      if (isMounted) {
        setMarkdown(result.traceMarkdown);
        setLoading(false);
      }
    };
    fetchTrace();
    return () => { isMounted = false; };
  }, [scenario.id, site.id]);

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4">
      {/* Backdrop */}
      <div className="absolute inset-0 bg-slate-900/60 backdrop-blur-sm" onClick={onClose}></div>

      {/* Modal Content */}
      <div className="relative bg-white rounded-xl shadow-2xl w-full max-w-2xl max-h-[85vh] flex flex-col overflow-hidden animate-in fade-in zoom-in duration-200">
        
        {/* Header */}
        <div className="flex items-center justify-between px-6 py-4 border-b border-slate-100 bg-slate-50">
          <div className="flex items-center gap-3">
             <div className="p-2 bg-indigo-100 text-indigo-700 rounded-lg">
               <BookOpen size={20} />
             </div>
             <div>
               <h2 className="font-bold text-slate-800">Inspector's Trace</h2>
               <p className="text-xs text-slate-500">Reasoning for {site.name} under {scenario.label}</p>
             </div>
          </div>
          <button onClick={onClose} className="p-2 text-slate-400 hover:text-slate-600 hover:bg-slate-200 rounded-full transition-colors">
            <X size={20} />
          </button>
        </div>

        {/* Body */}
        <div className="flex-1 overflow-y-auto p-6 bg-white">
          {loading ? (
            <div className="flex flex-col items-center justify-center h-64 space-y-4">
              <Loader2 className="w-8 h-8 text-indigo-600 animate-spin" />
              <p className="text-slate-500 font-medium animate-pulse">Consulting AI Inspector...</p>
            </div>
          ) : (
            <div className="prose prose-slate prose-sm max-w-none text-slate-600">
              {markdown ? (
                <ReactMarkdown
                  components={{
                    h1: ({node, ...props}) => <h1 className="text-xl font-bold text-slate-900 mt-6 mb-4" {...props} />,
                    h2: ({node, ...props}) => <h2 className="text-lg font-bold text-slate-800 mt-5 mb-3" {...props} />,
                    h3: ({node, ...props}) => <h3 className="text-base font-bold text-slate-800 mt-4 mb-2" {...props} />,
                    p: ({node, ...props}) => <p className="leading-relaxed mb-4" {...props} />,
                    ul: ({node, ...props}) => <ul className="list-disc ml-5 mb-4 space-y-1" {...props} />,
                    ol: ({node, ...props}) => <ol className="list-decimal ml-5 mb-4 space-y-1" {...props} />,
                    li: ({node, ...props}) => <li className="pl-1" {...props} />,
                    strong: ({node, ...props}) => <strong className="font-semibold text-slate-900" {...props} />,
                    blockquote: ({node, ...props}) => <blockquote className="border-l-4 border-indigo-200 pl-4 italic text-slate-500 my-4" {...props} />,
                  }}
                >
                  {markdown}
                </ReactMarkdown>
              ) : (
                <div className="text-red-500 flex items-center gap-2"><AlertCircle size={16}/> Failed to load trace content.</div>
              )}
            </div>
          )}
        </div>

        {/* Footer */}
        <div className="px-6 py-4 border-t border-slate-100 bg-slate-50 text-xs text-slate-400 text-center">
          Generated by TPA Inspector AI (Gemini). Evidence citations are simulated for this demo.
        </div>
      </div>
    </div>
  );
};

export default TraceView;