#!/usr/bin/env bash
# Quick reference for container management

echo "TPA Container Management Quick Reference"
echo "========================================"
echo ""
echo "Setup (first time):"
echo "  ./scripts/setup_env.sh                  # Configure UID/GID"
echo "  docker compose -f docker/compose.oss.yml up -d --build"
echo ""
echo "Start/Stop:"
echo "  docker compose -f docker/compose.oss.yml up -d       # Start base services"
echo "  ./scripts/docker_down.sh                             # Stop all containers"
echo "  ./scripts/docker_down.sh --images                    # Stop + remove images"
echo "  ./scripts/docker_down.sh --all                       # Stop + remove everything"
echo ""
echo "Models (on-demand):"
echo "  docker compose -f docker/compose.oss.yml --profile llm up -d tpa-llm"
echo "  docker compose -f docker/compose.oss.yml --profile vlm up -d tpa-vlm"
echo "  docker compose -f docker/compose.oss.yml --profile embeddings up -d tpa-embeddings"
echo ""
echo "Troubleshooting:"
echo "  ./scripts/cleanup_ghost_containers.sh   # Remove ghost containers"
echo "  ./scripts/fix_volume_permissions.sh     # Fix volume ownership"
echo "  docker compose -f docker/compose.oss.yml logs -f tpa-api  # View logs"
echo ""
echo "Health checks:"
echo "  curl http://localhost:8000/healthz      # API health"
echo "  docker compose -f docker/compose.oss.yml ps  # Service status"
echo "  nvidia-smi                              # GPU usage"
echo ""
